runtime: nodejs12
env: standard
service: default

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10

env_variables:
  NODE_ENV: development
  PORT: 5000

handlers:
  - url: /
    static_files: index.html
    require_matching_file: false
    upload: index.html
  - url: /(.*)
    static_files: \1
    require_matching_file: false
    upload: .*
  - url: .*
    script: auto
